version: "3.4"
services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: comuniteca
    ports:
      - 5432:5432
